#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.10
# from Racc grammer file "".
#

require 'racc/parser.rb'
module TPPlus
  class Parser < Racc::Parser


  include TPPlus::Nodes

  attr_reader :interpreter
  def initialize(scanner, interpreter = TPPlus::Interpreter.new)
    @scanner       = scanner
    @interpreter   = interpreter
    super()
  end

  def next_token
    t = @scanner.next_token
    @interpreter.line_count += 1 if t && t[0] == :NEWLINE

    #puts t.inspect
    t
  end

  def parse
    do_parse
    @interpreter
  rescue Racc::ParseError => e
    raise "Parse error on line #{@interpreter.line_count+1}: #{e}"
  end
##### State transition tables begin ###

racc_action_table = [
    59,    20,    33,    25,    24,    25,    41,    40,    47,    24,
   198,   237,   147,    25,    30,    60,    20,    33,    25,    24,
   147,    33,    34,   237,   152,    23,   238,   191,   145,    30,
   191,    41,    40,    47,   227,   191,   144,    34,   238,    33,
    23,    34,    54,    26,    57,   143,    27,    18,    19,    41,
    40,    47,    21,    22,    28,    33,    58,    33,    26,    34,
    33,    27,    18,    19,    53,    47,   157,    21,    22,    28,
    20,    33,    25,    24,    54,    34,    57,    34,   171,   215,
    34,    98,    97,    30,   212,   213,   214,   216,   142,   151,
    20,    34,    25,    24,    23,   141,    53,    81,    82,    85,
    86,    83,    84,    30,    87,    88,    90,    91,    92,    94,
    89,    93,    26,   140,    23,    27,    18,    19,    41,    40,
    47,    21,    22,    28,    70,    20,    33,    25,    24,    54,
   139,    57,    26,    71,    72,    27,    18,    19,    30,   189,
   190,    21,    22,    28,   -59,   -60,    34,   -59,   -60,    23,
   159,    53,    81,    82,    85,    86,    83,    84,   160,    87,
    88,    90,    91,    92,    94,    89,    93,    26,   137,   138,
    27,    18,    19,   161,    47,    47,    21,    22,    28,    20,
    33,    25,    24,    54,    54,    57,    57,    47,    47,   162,
   -57,   -58,    30,   -57,   -58,   163,    54,    54,    57,    57,
    34,    67,    47,    23,    68,    53,    53,    92,   164,   165,
    93,    54,   166,    57,    41,    40,    47,    47,    53,    53,
   168,    26,   130,   129,    27,    18,    19,    47,    47,   175,
    21,    22,    28,    53,    47,    47,    54,    54,    57,    57,
    47,    47,   124,    54,    54,    57,    57,   124,   157,    54,
    54,    57,    57,    41,    40,    47,   124,   178,    53,    53,
    41,    40,    47,   179,   180,    53,    53,    41,    40,    47,
   181,    53,    53,    81,    82,    85,    86,    83,    84,   182,
    87,    88,    90,    91,    92,    94,    89,    93,    41,    40,
    47,    41,    40,    47,   183,   184,    81,    82,    85,    86,
    83,    84,   131,    87,    88,    90,    91,    92,    94,    89,
    93,   118,   117,   115,   116,   113,   185,   114,   124,   112,
   124,    47,   119,   -74,    77,   136,   196,   197,   151,    41,
    40,    81,    82,    85,    86,    83,    84,    58,    87,    88,
    90,    91,    92,    94,    89,    93,    81,    82,    85,    86,
    83,    84,    60,    87,    88,    90,    91,    92,    94,    89,
    93,    81,    82,    85,    86,    83,    84,    75,    87,    88,
    90,    91,    92,    94,    89,    93,    81,    82,    85,    86,
    83,    84,   203,    87,    88,    90,    91,    92,    94,    89,
    93,    81,    82,    85,    86,    83,    84,    20,    87,    88,
    90,    91,    92,    94,    89,    93,    81,    82,    85,    86,
    83,    84,    73,    87,    88,    90,    91,    92,    94,    89,
    93,    81,    82,    85,    86,    83,    84,   203,    87,    88,
    90,    91,    92,    94,    89,    93,    81,    82,    85,    86,
    83,    84,   124,    87,    88,    90,    91,    92,    94,    89,
    93,    81,    82,    85,    86,    83,    84,   209,    87,    88,
    90,    91,    92,    94,    89,    93,   210,   211,    69,   217,
   218,   219,   220,   221,   222,   223,   224,    47,    20,    47,
    47,    20,   235,    43,   239,   240,   241,   242,   244,    42,
    36,   249,    47,   251 ]

racc_action_check = [
    23,     4,     4,     4,     4,   187,   219,   219,   219,   242,
   190,   226,   122,   186,     4,    23,     0,     0,     0,     0,
   121,   192,     4,   239,   127,     4,   226,   187,   118,     0,
   242,    22,    22,    22,   219,   186,   117,     0,   239,   120,
     0,   192,    22,     4,    22,   116,     4,     4,     4,   138,
   138,   138,     4,     4,     4,     2,    23,   195,     0,   120,
    38,     0,     0,     0,    22,    67,   131,     0,     0,     0,
    63,    63,    63,    63,    67,     2,    67,   195,   149,   208,
    38,    56,    56,    63,   208,   208,   208,   208,   115,   149,
    37,    63,    37,    37,    63,   114,    67,    63,    63,    63,
    63,    63,    63,    37,    63,    63,    63,    63,    63,    63,
    63,    63,    63,   113,    37,    63,    63,    63,    18,    18,
    68,    63,    63,    63,    32,    65,    65,    65,    65,    68,
   112,    68,    37,    32,    32,    37,    37,    37,    65,   177,
   177,    37,    37,    37,     9,    13,    65,     9,    13,    65,
   139,    68,    65,    65,    65,    65,    65,    65,   140,    65,
    65,    65,    65,    65,    65,    65,    65,    65,    99,    99,
    65,    65,    65,   141,    70,    79,    65,    65,    65,   147,
   147,   147,   147,    70,    79,    70,    79,    80,   130,   142,
     8,     6,   147,     8,     6,   143,    80,   130,    80,   130,
   147,    29,   129,   147,    29,    70,    79,    96,   144,   145,
    96,   129,   146,   129,   151,   151,   151,    77,    80,   130,
   148,   147,    72,    71,   147,   147,   147,    54,    26,   152,
   147,   147,   147,   129,    27,    53,    54,    26,    54,    26,
    42,    78,    69,    27,    53,    27,    53,    66,   155,    42,
    78,    42,    78,   222,   222,   222,   157,   159,    54,    26,
   198,   198,   198,   160,   161,    27,    53,    58,    58,    58,
   162,    42,    78,    76,    76,    76,    76,    76,    76,   163,
    76,    76,    76,    76,    76,    76,    76,    76,    21,    21,
    21,   220,   220,   220,   164,   165,    95,    95,    95,    95,
    95,    95,    76,    95,    95,    95,    95,    95,    95,    95,
    95,    59,    59,    59,    59,    59,   169,    59,   171,    59,
   172,   175,    60,    50,    48,    95,   188,   189,   123,    59,
    59,   126,   126,   126,   126,   126,   126,   191,   126,   126,
   126,   126,   126,   126,   126,   126,   134,   134,   134,   134,
   134,   134,    47,   134,   134,   134,   134,   134,   134,   134,
   134,   135,   135,   135,   135,   135,   135,    39,   135,   135,
   135,   135,   135,   135,   135,   135,   128,   128,   128,   128,
   128,   128,   196,   128,   128,   128,   128,   128,   128,   128,
   128,   154,   154,   154,   154,   154,   154,   197,   154,   154,
   154,   154,   154,   154,   154,   154,    49,    49,    49,    49,
    49,    49,    36,    49,    49,    49,    49,    49,    49,    49,
    49,   133,   133,   133,   133,   133,   133,   201,   133,   133,
   133,   133,   133,   133,   133,   133,   125,   125,   125,   125,
   125,   125,   203,   125,   125,   125,   125,   125,   125,   125,
   125,   153,   153,   153,   153,   153,   153,   204,   153,   153,
   153,   153,   153,   153,   153,   153,   205,   206,    30,   210,
   211,   212,   213,   214,   215,   216,   218,    28,    25,   221,
    24,   223,   225,    20,   228,   229,   230,   231,   234,    19,
     1,   243,   244,   246 ]

racc_action_pointer = [
    13,   490,    51,   nil,    -2,   nil,   146,   nil,   145,    99,
   nil,   nil,   nil,   100,   nil,   nil,   nil,   nil,    93,   431,
   456,   263,     6,    -2,   453,   475,   201,   207,   450,   156,
   451,   nil,    96,   nil,   nil,   nil,   412,    87,    56,   340,
   nil,   nil,   213,   nil,   nil,   nil,   nil,   335,   264,   376,
   263,   nil,   nil,   208,   200,   nil,    56,   nil,   242,   304,
   295,   nil,   nil,    67,   nil,   122,   223,    38,    93,   218,
   147,   195,   194,   nil,   nil,   nil,   243,   190,   214,   148,
   160,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   266,   166,   nil,   nil,   109,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    69,    52,    34,    27,   -16,   -25,   -33,   nil,
    35,   -26,   -34,   271,   nil,   406,   301,     6,   346,   175,
   161,    49,   nil,   391,   316,   331,   nil,   nil,    24,   124,
   132,   147,   163,   169,   182,   183,   165,   176,   173,    32,
   nil,   189,   171,   421,   361,   231,   nil,   232,   nil,   195,
   201,   202,   208,   217,   232,   233,   nil,   nil,   nil,   269,
   nil,   294,   296,   nil,   nil,   294,   nil,    88,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     8,     0,   267,   269,
   -48,   279,    17,   nil,   nil,    53,   365,   394,   235,   nil,
   nil,   410,   nil,   418,   398,   439,   407,   nil,    65,   nil,
   410,   443,   413,   414,   415,   416,   417,   nil,   417,   -19,
   266,   452,   228,   478,   nil,   423,   -18,   nil,   424,   426,
   427,   427,   nil,   nil,   428,   nil,   nil,   nil,   nil,    -6,
   nil,   nil,     3,   432,   465,   nil,   434,   nil,   nil,   nil,
   nil,   nil ]

racc_action_default = [
    -1,  -140,    -2,    -3,    -7,   -10,   -11,   -12,   -13,   -14,
   -15,   -16,   -17,   -18,   -19,   -20,   -21,   -22,  -140,  -140,
  -140,  -140,  -140,   -90,  -140,  -140,  -117,  -117,  -140,  -140,
  -140,   -84,  -140,  -135,  -136,  -137,  -140,    -5,    -6,  -140,
  -118,  -119,  -117,   -31,   -32,   -73,   -74,   -90,  -140,   -34,
  -113,   -91,   -92,  -117,  -117,  -112,  -140,  -116,   -38,  -140,
  -140,   -41,   -42,    -8,  -113,    -8,  -139,  -117,  -117,  -139,
  -117,  -140,  -140,   252,    -4,   -23,  -140,  -140,  -117,  -117,
  -117,   -98,   -99,  -100,  -101,  -102,  -103,  -104,  -105,  -106,
  -107,  -108,  -109,  -110,  -111,  -140,   -97,  -114,  -115,  -140,
   -36,   -39,   -40,   -85,  -120,  -121,  -122,  -123,  -124,  -125,
  -126,  -127,  -140,  -140,  -140,  -140,  -140,  -140,  -140,   -89,
    -9,   -62,   -62,  -140,  -138,   -55,   -56,  -140,   -86,  -117,
  -117,   -25,   -33,   -94,   -95,   -96,   -93,   -35,  -140,  -140,
  -140,  -140,  -140,  -140,  -140,  -140,  -140,    -8,  -140,   -52,
   -46,  -140,  -140,   -87,   -88,   -24,   -26,  -139,   -37,  -140,
  -140,  -140,  -140,  -140,  -140,  -140,   -43,   -61,   -44,  -140,
   -47,  -139,  -139,   -49,   -50,  -140,   -27,  -140,  -128,  -129,
  -130,  -131,  -132,  -133,  -134,   -45,  -140,  -140,  -140,  -140,
  -140,  -140,  -140,   -53,   -54,  -140,  -140,  -140,  -140,   -51,
   -48,   -63,   -64,  -139,  -140,  -140,  -140,   -65,  -140,   -28,
  -140,  -140,  -140,  -140,  -140,  -140,  -140,   -29,  -140,  -140,
  -140,  -140,  -140,  -140,   -30,  -140,  -140,   -80,  -140,  -140,
  -140,  -140,   -77,   -78,   -72,   -66,   -79,   -82,   -83,  -140,
   -67,   -68,  -140,  -140,  -140,   -81,  -140,   -75,   -76,   -70,
   -71,   -69 ]

racc_goto_table = [
    32,    39,    44,    48,    32,    62,   123,    37,   121,   127,
   122,   100,   193,   193,   150,   156,     2,   149,   236,    99,
    38,    46,    50,   169,    61,    49,   155,   202,    66,    63,
    65,   245,   207,   192,   195,   146,   148,    32,   172,   176,
   170,   101,   110,    37,   248,    76,   194,   194,   201,    74,
   225,   231,   246,   243,     1,   103,    95,    96,   102,   104,
   105,   106,   107,    32,   108,    32,   109,   111,   247,   nil,
   125,   126,   nil,   128,   nil,   nil,   nil,   132,   nil,   nil,
   nil,   133,   134,   135,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   158,   167,   nil,   nil,   nil,   nil,   177,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   186,   187,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   101,   nil,   nil,   nil,    37,   nil,   nil,   nil,   nil,
   nil,   nil,   153,   154,   173,   nil,   nil,   nil,   102,   nil,
   nil,   nil,   nil,   208,   nil,   nil,   nil,    32,   nil,   nil,
   nil,   174,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   188,   nil,   204,   nil,   nil,
   nil,   205,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   199,   206,   nil,
   200,   229,   226,   234,   nil,   233,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   228,
    46,   230,   232,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   250 ]

racc_goto_check = [
    25,    19,    26,    26,    25,    24,    23,     4,     5,    23,
     5,    28,    14,    14,    32,    22,     2,    30,    42,    27,
     2,    25,    25,    31,    25,    20,    21,    37,    25,    20,
    20,    42,    37,    34,    34,    29,    29,    25,    33,    22,
    32,    19,    19,     4,    10,    20,     9,     9,    36,     3,
    38,    39,    40,    41,     1,    43,    20,    20,    25,    51,
    52,    53,    54,    25,    55,    25,    56,    57,    14,   nil,
    20,    20,   nil,    20,   nil,   nil,   nil,    25,   nil,   nil,
   nil,    20,    20,    20,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,     5,   nil,   nil,   nil,   nil,    23,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    23,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    19,   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,
   nil,   nil,    20,    20,    19,   nil,   nil,   nil,    25,   nil,
   nil,   nil,   nil,    23,   nil,   nil,   nil,    25,   nil,   nil,
   nil,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    25,   nil,    24,   nil,   nil,
   nil,    19,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,    25,   nil,
     4,    26,    19,    24,   nil,    19,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    25,
    25,    25,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    25 ]

racc_goto_pointer = [
   nil,    54,    16,    12,     5,   -55,   nil,   nil,   nil,  -140,
  -198,   nil,   nil,   nil,  -174,   nil,   nil,   nil,   nil,   -17,
     3,  -105,  -116,   -60,   -20,     0,   -19,   -39,   -47,   -86,
  -106,  -126,  -109,  -113,  -153,   nil,  -148,  -169,  -169,  -171,
  -190,  -181,  -208,    -4,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     0,     1,     2,     3,     5,     7,     8,   nil ]

racc_goto_default = [
   nil,   nil,   120,     3,     4,   nil,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,    15,    16,    17,    45,
   nil,   nil,   nil,   nil,    31,    64,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    51,    52,    78,    79,    80,    55,
    56,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 64, :_reduce_none,
  1, 64, :_reduce_2,
  1, 65, :_reduce_3,
  3, 65, :_reduce_4,
  2, 65, :_reduce_5,
  2, 65, :_reduce_6,
  1, 65, :_reduce_7,
  0, 68, :_reduce_none,
  1, 68, :_reduce_9,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  3, 80, :_reduce_23,
  5, 80, :_reduce_24,
  0, 84, :_reduce_none,
  1, 84, :_reduce_26,
  2, 84, :_reduce_27,
  6, 85, :_reduce_28,
  7, 85, :_reduce_29,
  8, 85, :_reduce_30,
  2, 87, :_reduce_31,
  2, 78, :_reduce_32,
  4, 79, :_reduce_33,
  2, 79, :_reduce_34,
  4, 77, :_reduce_35,
  1, 90, :_reduce_36,
  3, 90, :_reduce_37,
  0, 90, :_reduce_38,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  2, 73, :_reduce_41,
  2, 72, :_reduce_42,
  5, 75, :_reduce_43,
  5, 75, :_reduce_44,
  6, 81, :_reduce_45,
  1, 93, :_reduce_46,
  2, 93, :_reduce_47,
  5, 95, :_reduce_48,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  4, 94, :_reduce_51,
  0, 94, :_reduce_none,
  1, 97, :_reduce_none,
  1, 97, :_reduce_none,
  3, 76, :_reduce_55,
  3, 76, :_reduce_56,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  2, 92, :_reduce_61,
  0, 92, :_reduce_none,
  8, 71, :_reduce_63,
  1, 99, :_reduce_64,
  2, 99, :_reduce_65,
  6, 100, :_reduce_66,
  6, 100, :_reduce_67,
  6, 100, :_reduce_68,
  8, 100, :_reduce_69,
  7, 100, :_reduce_70,
  2, 104, :_reduce_71,
  0, 104, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 103, :_reduce_none,
  1, 103, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  2, 101, :_reduce_79,
  1, 101, :_reduce_80,
  3, 101, :_reduce_81,
  1, 105, :_reduce_82,
  1, 105, :_reduce_83,
  1, 74, :_reduce_84,
  3, 69, :_reduce_85,
  3, 70, :_reduce_86,
  4, 70, :_reduce_87,
  4, 70, :_reduce_88,
  3, 88, :_reduce_89,
  1, 88, :_reduce_90,
  1, 83, :_reduce_91,
  1, 83, :_reduce_92,
  3, 83, :_reduce_93,
  3, 108, :_reduce_94,
  3, 108, :_reduce_95,
  3, 108, :_reduce_96,
  2, 108, :_reduce_97,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 111, :_reduce_none,
  1, 111, :_reduce_none,
  1, 111, :_reduce_none,
  1, 111, :_reduce_none,
  1, 111, :_reduce_none,
  1, 107, :_reduce_none,
  1, 107, :_reduce_none,
  2, 112, :_reduce_114,
  2, 112, :_reduce_115,
  1, 113, :_reduce_none,
  0, 113, :_reduce_none,
  1, 82, :_reduce_118,
  1, 82, :_reduce_119,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  4, 120, :_reduce_128,
  4, 119, :_reduce_129,
  4, 118, :_reduce_130,
  4, 114, :_reduce_131,
  4, 117, :_reduce_132,
  4, 115, :_reduce_133,
  4, 116, :_reduce_134,
  1, 121, :_reduce_135,
  1, 67, :_reduce_136,
  1, 67, :_reduce_137,
  1, 86, :_reduce_138,
  0, 86, :_reduce_none ]

racc_reduce_n = 140

racc_shift_n = 252

racc_token_table = {
  false => 0,
  :error => 1,
  :ASSIGN => 2,
  :AT_SYM => 3,
  :COMMENT => 4,
  :JUMP => 5,
  :IO_METHOD => 6,
  :INPUT => 7,
  :OUTPUT => 8,
  :NUMREG => 9,
  :POSREG => 10,
  :VREG => 11,
  :SREG => 12,
  :POSITION => 13,
  :TIME_SEGMENT => 14,
  :ARG => 15,
  :MOVE => 16,
  :DOT => 17,
  :TO => 18,
  :AT => 19,
  :TERM => 20,
  :OFFSET => 21,
  :SKIP => 22,
  :SEMICOLON => 23,
  :NEWLINE => 24,
  :REAL => 25,
  :DIGIT => 26,
  :WORD => 27,
  :EQUAL => 28,
  :UNITS => 29,
  :EEQUAL => 30,
  :NOTEQUAL => 31,
  :GTE => 32,
  :LTE => 33,
  :LT => 34,
  :GT => 35,
  :BANG => 36,
  :PLUS => 37,
  :MINUS => 38,
  :STAR => 39,
  :SLASH => 40,
  :DIV => 41,
  :AND => 42,
  :OR => 43,
  :MOD => 44,
  :IF => 45,
  :ELSE => 46,
  :END => 47,
  :UNLESS => 48,
  :WAIT_FOR => 49,
  :WAIT_UNTIL => 50,
  :TIMEOUT => 51,
  :AFTER => 52,
  :MAX_SPEED => 53,
  :FANUC_USE => 54,
  :FANUC_SET => 55,
  :CASE => 56,
  :WHEN => 57,
  "(" => 58,
  ")" => 59,
  "," => 60,
  "[" => 61,
  "]" => 62 }

racc_nt_base = 63

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ASSIGN",
  "AT_SYM",
  "COMMENT",
  "JUMP",
  "IO_METHOD",
  "INPUT",
  "OUTPUT",
  "NUMREG",
  "POSREG",
  "VREG",
  "SREG",
  "POSITION",
  "TIME_SEGMENT",
  "ARG",
  "MOVE",
  "DOT",
  "TO",
  "AT",
  "TERM",
  "OFFSET",
  "SKIP",
  "SEMICOLON",
  "NEWLINE",
  "REAL",
  "DIGIT",
  "WORD",
  "EQUAL",
  "UNITS",
  "EEQUAL",
  "NOTEQUAL",
  "GTE",
  "LTE",
  "LT",
  "GT",
  "BANG",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "DIV",
  "AND",
  "OR",
  "MOD",
  "IF",
  "ELSE",
  "END",
  "UNLESS",
  "WAIT_FOR",
  "WAIT_UNTIL",
  "TIMEOUT",
  "AFTER",
  "MAX_SPEED",
  "FANUC_USE",
  "FANUC_SET",
  "CASE",
  "WHEN",
  "\"(\"",
  "\")\"",
  "\",\"",
  "\"[\"",
  "\"]\"",
  "$start",
  "program",
  "statements",
  "statement",
  "terminator",
  "block",
  "definition",
  "assignment",
  "motion_statement",
  "jump",
  "io_method",
  "label_definition",
  "conditional",
  "inline_conditional",
  "program_call",
  "use_statement",
  "set_statement",
  "wait_statement",
  "case_statement",
  "number",
  "expression",
  "wait_modifiers",
  "wait_modifier",
  "swallow_newlines",
  "label",
  "var",
  "indirectable",
  "args",
  "arg",
  "else_block",
  "case_conditions",
  "case_else",
  "case_condition",
  "case_allowed_condition",
  "case_allowed_statement",
  "inlineable",
  "motion_modifiers",
  "motion_modifier",
  "speed",
  "time",
  "time_seg_actions",
  "optional_lpos_arg",
  "units",
  "definable",
  "factor",
  "operator",
  "relop",
  "addop",
  "mulop",
  "signed_number",
  "sign",
  "numreg",
  "output",
  "input",
  "posreg",
  "position",
  "vreg",
  "argument",
  "comment" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

def _reduce_2(val, _values, result)
 @interpreter.nodes = val[0].flatten 
    result
end

def _reduce_3(val, _values, result)
 result = val 
    result
end

def _reduce_4(val, _values, result)
 result = val[0] << val[1] << val[2] 
    result
end

def _reduce_5(val, _values, result)
 result = val[0] << val[1] 
    result
end

def _reduce_6(val, _values, result)
 result = [val[0]] << val[1] 
    result
end

def _reduce_7(val, _values, result)
 result = [val[0]] 
    result
end

# reduce 8 omitted

def _reduce_9(val, _values, result)
 result = val[0] 
    result
end

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

def _reduce_23(val, _values, result)
 result = WaitForNode.new(val[1], val[2]) 
    result
end

def _reduce_24(val, _values, result)
 result = WaitUntilNode.new(val[2],val[4]) 
    result
end

# reduce 25 omitted

def _reduce_26(val, _values, result)
 result = val[0] 
    result
end

def _reduce_27(val, _values, result)
 result = val[0].merge(val[1]) 
    result
end

def _reduce_28(val, _values, result)
 result = { label: val[4] } 
    result
end

def _reduce_29(val, _values, result)
 result = { timeout: [val[4],val[5]] } 
    result
end

def _reduce_30(val, _values, result)
 result = { timeout: [val[4],val[6]] } 
    result
end

def _reduce_31(val, _values, result)
 result = val[1] 
    result
end

def _reduce_32(val, _values, result)
 result = UseNode.new(val[0],val[1]) 
    result
end

def _reduce_33(val, _values, result)
 result = SetNode.new(val[0],val[1],val[3]) 
    result
end

def _reduce_34(val, _values, result)
 result = SetNode.new(val[0],nil,val[1]) 
    result
end

def _reduce_35(val, _values, result)
 result = CallNode.new(val[0],val[2]) 
    result
end

def _reduce_36(val, _values, result)
 result = [val[0]] 
    result
end

def _reduce_37(val, _values, result)
 result = val[0] << val[2] 
    result
end

def _reduce_38(val, _values, result)
 result = [] 
    result
end

# reduce 39 omitted

# reduce 40 omitted

def _reduce_41(val, _values, result)
 result = IOMethodNode.new(val[0],val[1]) 
    result
end

def _reduce_42(val, _values, result)
 result = JumpNode.new(val[1]) 
    result
end

def _reduce_43(val, _values, result)
 result = ConditionalNode.new("if",val[1],val[2],val[3]) 
    result
end

def _reduce_44(val, _values, result)
 result = ConditionalNode.new("unless",val[1],val[2],val[3]) 
    result
end

def _reduce_45(val, _values, result)
 result = CaseNode.new(val[1],val[3],val[4]) 
    result
end

def _reduce_46(val, _values, result)
 result = val 
    result
end

def _reduce_47(val, _values, result)
 result = val[0] << val[1] << val[2] 
    result
end

def _reduce_48(val, _values, result)
 result = CaseConditionNode.new(val[1],val[3]) 
    result
end

# reduce 49 omitted

# reduce 50 omitted

def _reduce_51(val, _values, result)
 result = CaseConditionNode.new(nil,val[2]) 
    result
end

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

def _reduce_55(val, _values, result)
 result = InlineConditionalNode.new("if",val[2],val[0]) 
    result
end

def _reduce_56(val, _values, result)
 result = InlineConditionalNode.new("unless",val[2],val[0]) 
    result
end

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

def _reduce_61(val, _values, result)
 result = val[1] 
    result
end

# reduce 62 omitted

def _reduce_63(val, _values, result)
 result = MotionNode.new(val[0],val[5],val[7]) 
    result
end

def _reduce_64(val, _values, result)
 result = val 
    result
end

def _reduce_65(val, _values, result)
 result = val[0] << val[1] 
    result
end

def _reduce_66(val, _values, result)
 result = SpeedNode.new(val[4]) 
    result
end

def _reduce_67(val, _values, result)
 result = TerminationNode.new(val[4]) 
    result
end

def _reduce_68(val, _values, result)
 result = OffsetNode.new(val[4]) 
    result
end

def _reduce_69(val, _values, result)
 result = TimeNode.new(val[2],val[4],val[6]) 
    result
end

def _reduce_70(val, _values, result)
 result = SkipNode.new(val[4],val[5]) 
    result
end

def _reduce_71(val, _values, result)
 result = val[1] 
    result
end

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

def _reduce_79(val, _values, result)
 result = [val[0],val[1]] 
    result
end

def _reduce_80(val, _values, result)
 result = [:max_speed,:max_speed] 
    result
end

def _reduce_81(val, _values, result)
 result = [val[0],val[2]] 
    result
end

def _reduce_82(val, _values, result)
 result = UnitsNode.new(val[0]) 
    result
end

def _reduce_83(val, _values, result)
 result = UnitsNode.new(val[0]) 
    result
end

def _reduce_84(val, _values, result)
 result = LabelDefinitionNode.new(val[0]) 
    result
end

def _reduce_85(val, _values, result)
 result = DefinitionNode.new(val[0],val[2]) 
    result
end

def _reduce_86(val, _values, result)
 result = AssignmentNode.new(val[0],val[2]) 
    result
end

def _reduce_87(val, _values, result)
 result = AssignmentNode.new(
                                           val[0],
                                           ExpressionNode.new(val[0],val[1],val[3])
                                         )
                                       
    result
end

def _reduce_88(val, _values, result)
 result = AssignmentNode.new(
                                           val[0],
                                           ExpressionNode.new(val[0],val[1],val[3])
                                         )
                                       
    result
end

def _reduce_89(val, _values, result)
 result = VarMethodNode.new(val[0],val[2]) 
    result
end

def _reduce_90(val, _values, result)
 result = VarNode.new(val[0]) 
    result
end

def _reduce_91(val, _values, result)
 result = val[0] 
    result
end

def _reduce_92(val, _values, result)
 result = val[0] 
    result
end

def _reduce_93(val, _values, result)
 val[1].grouped = true; result = val[1] 
    result
end

def _reduce_94(val, _values, result)
 result = ExpressionNode.new(val[0],val[1],val[2]) 
    result
end

def _reduce_95(val, _values, result)
 result = ExpressionNode.new(val[0],val[1],val[2]) 
    result
end

def _reduce_96(val, _values, result)
 result = ExpressionNode.new(val[0],val[1],val[2]) 
    result
end

def _reduce_97(val, _values, result)
 result = ExpressionNode.new(val[1],val[0],nil) 
    result
end

# reduce 98 omitted

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

# reduce 112 omitted

# reduce 113 omitted

def _reduce_114(val, _values, result)
 val[1] = val[1].to_i * -1 if val[0] == "-"; result = DigitNode.new(val[1]) 
    result
end

def _reduce_115(val, _values, result)
 val[1] = val[1].to_f * -1 if val[0] == "-"; result = RealNode.new(val[1]) 
    result
end

# reduce 116 omitted

# reduce 117 omitted

def _reduce_118(val, _values, result)
 result = DigitNode.new(val[0]) 
    result
end

def _reduce_119(val, _values, result)
 result = RealNode.new(val[0]) 
    result
end

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

# reduce 127 omitted

def _reduce_128(val, _values, result)
 result = ArgumentNode.new(val[2].to_i) 
    result
end

def _reduce_129(val, _values, result)
 result = VisionRegisterNode.new(val[2].to_i) 
    result
end

def _reduce_130(val, _values, result)
 result = PositionNode.new(val[2].to_i) 
    result
end

def _reduce_131(val, _values, result)
 result = NumregNode.new(val[2].to_i) 
    result
end

def _reduce_132(val, _values, result)
 result = PosregNode.new(val[2].to_i) 
    result
end

def _reduce_133(val, _values, result)
 result = IONode.new(val[0], val[2].to_i) 
    result
end

def _reduce_134(val, _values, result)
 result = IONode.new(val[0], val[2].to_i) 
    result
end

def _reduce_135(val, _values, result)
 result = CommentNode.new(val[0]) 
    result
end

def _reduce_136(val, _values, result)
 result = TerminatorNode.new 
    result
end

def _reduce_137(val, _values, result)
 result = val[0] 
    result
end

def _reduce_138(val, _values, result)
 result = TerminatorNode.new 
    result
end

# reduce 139 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module TPPlus
